AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  PrefixParameter:
    Type: String
    Default: mlflow
    Description: Prefix for ddb tables
  RCUParameter:
    Type: Number
    Default: 1
    Description: Read Capacity Units for DynamoDb tables
  WCUParameter:
    Type: Number
    Default: 1
    Description: Write Capacity Units for DynamoDb tables
Resources:
  ExperimentTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "experiment_id"
          AttributeType: "N"
        -
          AttributeName: "lifecycle_stage"
          AttributeType: "S"
        -
          AttributeName: "name"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "experiment_id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: !Ref RCUParameter
        WriteCapacityUnits: !Ref WCUParameter
      GlobalSecondaryIndexes:
        -
          IndexName: LifeCycleStage
          KeySchema:
            -
              AttributeName: "lifecycle_stage"
              KeyType: "HASH"
            -
              AttributeName: "name"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
          ProvisionedThroughput:
            ReadCapacityUnits: !Ref RCUParameter
            WriteCapacityUnits: !Ref WCUParameter
      TableName:
        !Join
          - '_'
          - - !Ref PrefixParameter
            - 'experiment'
  RunTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "run_uuid"
          AttributeType: "S"
        -
          AttributeName: "experiment_id"
          AttributeType: "N"
        -
          AttributeName: "lifecycle_stage"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "run_uuid"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: !Ref RCUParameter
        WriteCapacityUnits: !Ref WCUParameter
      GlobalSecondaryIndexes:
        -
          IndexName: LifeCycleStage
          KeySchema:
            -
              AttributeName: "lifecycle_stage"
              KeyType: "HASH"
            -
              AttributeName: "experiment_id"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "KEYS_ONLY"
          ProvisionedThroughput:
            ReadCapacityUnits: !Ref RCUParameter
            WriteCapacityUnits: !Ref WCUParameter
      TableName:
        !Join
          - '_'
          - - !Ref PrefixParameter
            - 'run'
  RunTagTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "run_uuid"
          AttributeType: "S"
        -
          AttributeName: "key"
          AttributeType: "S"
        # -
        #   AttributeName: "value"
        #   AttributeType: "S"
      KeySchema:
        -
          AttributeName: "run_uuid"
          KeyType: "HASH"
        -
          AttributeName: "key"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: !Ref RCUParameter
        WriteCapacityUnits: !Ref WCUParameter
      TableName:
        !Join
          - '_'
          - - !Ref PrefixParameter
            - 'run'
            - 'tag'
  RunParamTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "run_uuid"
          AttributeType: "S"
        -
          AttributeName: "key"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "run_uuid"
          KeyType: "HASH"
        -
          AttributeName: "key"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: !Ref RCUParameter
        WriteCapacityUnits: !Ref WCUParameter
      TableName:
        !Join
          - '_'
          - - !Ref PrefixParameter
            - 'run'
            - 'param'
  RunMetricTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "run_uuid"
          AttributeType: "S"
        -
          AttributeName: "key"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "run_uuid"
          KeyType: "HASH"
        -
          AttributeName: "key"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: !Ref RCUParameter
        WriteCapacityUnits: !Ref WCUParameter
      TableName:
        !Join
          - '_'
          - - !Ref PrefixParameter
            - 'run'
            - 'metric'
